# Generated by Django 5.1.2 on 2024-11-29 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tipoPlaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
                ("img", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Plaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
                ("img", models.CharField(max_length=255)),
                (
                    "fk_Tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sanidad.tipoplaga",
                    ),
                ),
            ],
        ),
    ]
