# Generated by Django 5.1.2 on 2024-11-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TipoPlaga",
        ),
    ]
