# Generated by Django 5.1.2 on 2024-12-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Afecciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fk_Plantacion", models.IntegerField()),
                ("fechaEncuentro", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("ST", "ST"), ("EC", "EC"), ("EL", "EL")],
                        default="ST",
                        max_length=30,
                    ),
                ),
                (
                    "fk_Plaga",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sanidad.plaga",
                    ),
                ),
            ],
        ),
    ]
