# Generated by Django 5.1.2 on 2024-12-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0002_afecciones"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiposControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
