# Generated by Django 5.1.2 on 2024-12-05 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0003_tiposcontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Controles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fechaControl", models.DateField()),
                (
                    "fk_Afeccion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sanidad.afecciones",
                    ),
                ),
                (
                    "fk_TipoControl",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sanidad.tiposcontrol",
                    ),
                ),
            ],
        ),
    ]
