# Generated by Django 5.1.2 on 2024-11-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="tipo",
        ),
    ]
