# Generated by Django 5.1.2 on 2024-11-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sanidad", "0004_delete_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
                ("img", models.CharField(max_length=255)),
            ],
        ),
    ]
