# Generated by Django 5.1.2 on 2024-12-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0004_controles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductosControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("precio", models.IntegerField()),
                ("compuestoActivo", models.CharField(max_length=20)),
                ("fichaTecnica", models.TextField()),
                ("contenido", models.IntegerField()),
                ("tipoContenido", models.CharField(max_length=10)),
                ("unidades", models.SmallIntegerField()),
            ],
        ),
    ]
