# Generated by Django 5.1.2 on 2024-12-05 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0005_productoscontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsoProductosControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidadProducto", models.IntegerField()),
                (
                    "fk_Control",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sanidad.controles",
                    ),
                ),
                (
                    "fk_ProductoControl",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sanidad.productoscontrol",
                    ),
                ),
            ],
        ),
    ]
