# Generated by Django 5.1.2 on 2024-11-24 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sanidad", "0005_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tipo",
            new_name="tipoPlaga",
        ),
    ]
