# Generated by Django 5.1.2 on 2024-11-04 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('unidades', models.IntegerField()),
                ('fechaSiembra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=150)),
                ('precio', models.IntegerField()),
                ('unidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposDesecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cosechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fk_Cultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha', models.DateField()),
                ('fk_Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fk_Cultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Desechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('fk_Cultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cultivos')),
                ('fk_TipoDesecho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.tiposdesecho')),
            ],
        ),
        migrations.CreateModel(
            name='UsosProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.IntegerField()),
                ('fk_Actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.actividades')),
                ('fk_Insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnitario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fk_Cosecha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cosechas')),
            ],
        ),
    ]
