# Generated by Django 5.0.2 on 2024-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correoElectronico',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
