# Generated by Django 5.0.2 on 2024-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correoElectronico',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
