# Generated by Django 5.0.2 on 2024-11-22 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamX', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamY', models.DecimalField(decimal_places=2, max_digits=6)),
                ('posX', models.DecimalField(decimal_places=2, max_digits=6)),
                ('posY', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('tamX', models.PositiveSmallIntegerField()),
                ('tamY', models.PositiveSmallIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('posX', models.DecimalField(decimal_places=2, max_digits=6)),
                ('posY', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='HumedadTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('porcentaje', models.PositiveIntegerField()),
                ('fk_Eras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronica.eras')),
            ],
        ),
        migrations.AddField(
            model_name='eras',
            name='fk_lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eras', to='electronica.lote'),
        ),
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fk_Eras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_readings', to='electronica.eras')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('TEM', 'Temperatura'), ('LUM', 'Iluminación'), ('HUM_A', 'Humedad Ambiental'), ('VIE', 'Velocidad del Viento')], max_length=6)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='electronica.lote')),
            ],
        ),
    ]
